version: '3.5'
services:
  web:
    image: caddy-frontend:latest
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./caddy-data:/data:z
      - ./Caddyfile:/etc/caddy/Caddyfile:z
      - ./site:/srv:z
      - ./caddy-config:/config:z
    ports:
      - ${APP_PORT}:${SR_PORT}
      - ${APP_TLS_PORT}:${SR_TLS_PORT}
    depends_on:
      - video-gateway

  sr-admin-gui:
    image: sr-admin-gui:latest
    restart: unless-stopped
    env_file: .env
    depends_on:
      - nats-proxy
    volumes:
      - ./.env:/var/www/html/.env:z
      - ./sr-admin-data:/data:z
    expose:
      - 80

  nats:
    image: nats:latest
    restart: unless-stopped
    expose:
      - 80
      - 4222

  nats-proxy:
    image: nats-proxy:latest
    restart: unless-stopped
    depends_on:
      - nats
    expose:
      - 80

  video-transcoder:
    image: video-transcoder:latest
    restart: unless-stopped
    depends_on:
      - nats
      - video-gateway
    env_file: .env
    volumes:
      - ./vt-data:/etc/supervisor/conf.d:z
    expose:
      - 80

  video-gateway:
    image: video-gateway:latest
    restart: unless-stopped
    env_file: .env
    expose:
      - 80